netlify/plugins

- README.md
- plugins.json
👋 Recently been experimenting with build plugins after an idea popped into my head. Some SSGs only deal with files, which makes it hard to integrate with the Ghost Content API. 
So what if there could be a build plugin that generated the files from the API before the build began? This plugin does exactly that! Mainly for Jekyll users, but the configuration options allow for other SSGs too.
Thanks for inviting me to the beta, and for all the Netlify stuff you do ✌️
> Add netlify-plugin-ghost-markdown to plugins list

- README.md
- plugins.json
- scripts/docs.js
Solves #4 adding `author` property per plugin.
It also renames `name` property as `package`, and adds a `name` property to avoid humanizing from IDs.
> Add author and name per plugin

- README.md
- plugins.json
There are [some issues](https://github.com/netlify/build/issues/1069#issuecomment-606057886) with the [Gatsby plugin](https://github.com/jlengstorf/netlify-plugin-gatsby-cache) which currently make builds crash. 
We should temporarily hide this plugin from the UI until those issues are fixed.
Note: this is a featured plugin, so do we also need to update this in the database?
> Temporarily hide Gatsby plugin from the UI.

- README.md
- plugins.json
This PR adds Gatsby plugin again, effectively reverting #13.
This should be merged only once the plugin is stable, including the issues listed [here](https://github.com/netlify/build/issues/1069#issuecomment-606057886).
> Add Gatsby plugin again

- README.md
- plugins.json
I created this plugin which makes Redwood production deploys MUCH easier until Prisma gets around to fixing [this issue](https://github.com/prisma/prisma2/issues/1487), but it should be helpful to anyone deploying Prisma to production.
> Adds netlify-plugin-prisma-provider

- README.md
- plugins.json
All plugins listed in https://github.com/netlify/plugins/blob/master/plugins.json now display in the Netlify UI. To ensure a consistent installation experience all plugins listed there, I did a survey of all plugins in the list and made PRs to update their READMEs a few weeks ago.
There are a few that still need some updates, so I'm removing them from the list for now. They can be re-added when they're up to date and tested!
> Remove plugins with outdated instructions

- README.md
- plugins.json
Hi. After having created the inline source plugin, I realized it’d be great to have a plugin to automatically inline critical CSS across many pages. [`critical`](https://github.com/addyosmani/critical) makes this very easy, so today I spent some time to create a [plugin](https://github.com/Tom-Bonnike/netlify-plugin-inline-critical-css) with sensible defaults. I tried it on a small Jekyll website and it seems to work as expected, but I’d love if you folks could also test it on your own websites before merging.
---
One small issue is that `critical` relies on Node v10 and, as you [probably know](https://github.com/netlify/build/issues/1239), the Ubuntu Xenial build image still uses v8 by default. I think [this issue](https://github.com/netlify/build/issues/1247) is a great idea, most users …
> Add inline critical CSS plugin

- plugins.json
This version should contain a fix for https://github.com/Tom-Bonnike/netlify-plugin-inline-critical-css/issues/3.
> Bump inline critical CSS plugin version

- README.md
Currently plugins.json file's url is broken due to typo. This PR fixes that.
> Fix plugins.json file url typo in README.md

- plugins.json
Support for some deprecated syntax used by few plugins is being removed. This will break those plugins, making builds using them crash in production.
This PR temporarily removes those plugins from Netlify UI.
PRs were sent to each of those plugins to use the new syntax, as listed [here](https://github.com/netlify/build/issues/1068#issuecomment-631741188). 
We should re-enable each of those plugins as soon as: 
1. Those PRs are merged
2. A new npm release is made
3. A PR is sent to this repository to update the `version` field in `plugins.json`
The list of plugins is:
- `netlify-plugin-get-env-vars` by @shortdiv ([PR 1](https://github.com/shortdiv/netlify-plugin-get-env-vars/pull/4))
- `netlify-plugin-prerender-spa` by @shortdiv ([PR …
> Temporarily disable some plugins

- plugins.json
This upgrades the `version` field of all plugins in `plugins.json`.
In the future, we will want plugin authors to submit PRs to do this update. But for the upcoming release, we should make sure those plugins use the latest versions. Most of those updates are fixing important bugs.
> Upgrade plugins versions

- plugins.json
This updates the version of `@netlify/plugin-sitemap` to include a fix with the latest version of Netlify Build.
> Update `@netlify/plugin-sitemap` version

- plugins.json
This upgrades the version of the Gatsby cache plugin to include the latest changes from Netlify Build.
> Upgrade version of Gatsby cache plugin

- plugins.json
Deactivating the following plugins:
- netlify-plugin-brand-guardian (@tzmanics )
- netlify-plugin-rss (@sw-yx )
- netlify-plugin-add-instagram (@philhawksworth )
These plugins require `inputs` to be set, but this can't be done in the Netlify UI. When possible, configure your plugin to work with a config-free default, or if some config must be required, allow them to be set via env vars. (More details in the new [plugin author guidelines](https://github.com/netlify/plugins/blob/master/docs/guidelines.md).)
> Deactivate plugins requiring inputs

- plugins.json
1.1.0 contains an update to `critical` that improves the loading strategy for uncritical CSS files.
It now uses `media` switching instead of outputting a `loadCSS` script in the head.
**Test plan**
See this successful build: https://app.netlify.com/sites/tombonnike/deploys/5ecf96d16ae0cc00063ec34d
It now uses the `media` font loading strategy, as expected:
⚠️ It seems like the “Bundle CSS” post-processing asset optimization messes up attributes, I opened an issue on the Build repository : https://github.com/netlify/build/issues/1384
> Bump inline-critical-css to 1.1.0

- plugins.json
the plugin includes stopword removal at source and text truncation to meet algolia community-account export limits by default (each object needs to be below 10k bytes)
**Test plan**
output of build with 0.3.0 https://vonage-dev-blog.netlify.app/build.output
once built, your route will include a searchIndex.json, the changes being that the text value of each object should now be less than your character limit, which has the result of limiting each object in the array to less than 10k bytes by default, which meets the restrictions of the algolia community-account export limits.
> bumping netlify-plugin-algolia-index version

- plugins.json
[Version 1.1.1](https://github.com/Tom-Bonnike/netlify-plugin-inline-critical-css/commit/f0b181d345c9b74428057fa5ee76c95dd398ea86) stops processing multiple HTML files concurrently to try and fix:
- https://github.com/Tom-Bonnike/netlify-plugin-inline-critical-css/issues/5 (lingering puppeteer processes)
- https://github.com/Tom-Bonnike/netlify-plugin-inline-critical-css/issues/3 (out of memory issues)
**Test plan**
https://app.netlify.com/sites/tombonnike/deploys/5ed0f71664437d0007563b2e
Obviously my test project is small, but if it works on one page it will work on multiple.
Not sure about the performance impact of that change, but it’s worth trying it to see if we get less errors. :)
> Bump netlify-plugin-inline-critical-css to 1.1.1

- docs/PULL_REQUEST_TEMPLATE.md
Related to #69.
This adds a npm diff to our PR template, so it's easy to check difference on plugin updates.
> Add npm diff to PR template

- plugins.json
This is a plugin for Dareboost customers, so that they can automatically add an event matching the successful build into their monitoring graph, and launch new pages analyses on their target.
Most of the configuration is done through `inputs`, except for the Dareboost API token that you need to define in an env. variable (I didn't want people committing their token by mistake on a public repo). The token is not logged during the build ([example](https://app.netlify.com/sites/borisschapira/deploys/5ed17a00e9063e00061ca9c6)).
**Next:** trying to understand how to configure, in this `netlify.toml` file, different plugin inputs for different branches (or restrict the execution of a plugin to one branch only).
**Are you adding a plugin …
> Adds Dareboost plugin

- .github/workflows/npmDiff.yml
- scripts/npm-diff.js
Follow up on https://github.com/netlify/plugins/issues/69
Uses a token with write permissions to support commenting on PRs coming from forks.
Also adds some error handling and reporting
> ci(npm-diff): use custom token with write permissions

- plugins.json
https://diff.intrinsic.com/netlify-plugin-chromium/1.1.1/1.1.4
**Test plan**
https://app.netlify.com/sites/amazing-morse-5b1303/deploys/5ee27b6145fc4e0007a159df
Between 8:44:57 and 8:45:27 the plugin is triggered and you can see Chromium being installed. Then at 8:46:24 Lighthouse CI is triggered and Chromium is recognized as available, thus further steps of Lighthouse process are performed.
> Bump and activate netlify-plugin-chromium

- plugins.json
- Fix for https://github.com/Tom-Bonnike/netlify-plugin-inline-critical-css/issues/8 (`critical` bump)
- Attempts at fixing (or at least limiting) https://github.com/Tom-Bonnike/netlify-plugin-inline-critical-css/issues/5
https://diff.intrinsic.com/netlify-plugin-inline-critical-css/1.1.1/1.1.3
**Test plan**
https://app.netlify.com/sites/tombonnike/deploys/5eecf18b59c7d0bb5d2f651f
> Bump netlify-plugin-inline-critical-css to 1.1.3

- plugins.json
adds netlify-plugin-gridsome-cache
If updating a previously added package, create a diff at [diff.intrinsic.com](https://diff.intrinsic.com) and provide a link to the diff here.
Example link: https://diff.intrinsic.com/@netlify/plugin-sitemap/0.3.3/0.3.4
**Test plan**
> updates plugins.json to add gridsome cache plugin

- plugins.json
https://diff.intrinsic.com/netlify-plugin-visual-diff/1.1.3/1.2.0
**Test plan**
> chore: bump visual diff version to 1.2.0

- docs/PULL_REQUEST_TEMPLATE.md
The manual step is no longer required as we do it automatically via a Netlifunction:
https://github.com/netlify/plugins/blob/d8421b4fa305267fe078e8658dd851e749b0596d/functions/npm-diff.js
> docs(pr-template): remove manual npm diff instruction

- plugins.json
**Test plan**
Basically, many people who use next as static export cannot use dynamic routes with Netlify unless they will going to **manually** write redirects. This plugin automate all of that
Full demo: https://demo-netlify-plugin-next-dynamic.netlify.app/
Source: https://github.com/Brikl/demo-netlify-plugin-next-dynamic
Successful deploy log: https://app.netlify.com/sites/demo-netlify-plugin-next-dynamic/deploys/5f1986636a6fd38c42e29609
> feat: add netlify-plugin-next-dynamic

- plugins.json
An update to the Algolia plugin got merged by #98.
This update includes some breaking changes: some additional environment variables (with Algolia credentials) are now required.
Unfortunately, we don't support breaking changes in plugins yet. We are still working on what the best experience for plugin users is when it comes to major releases. This means this update would make the builds of every user of that plugin break.
This PR reverts #98 so we can think of a solution to this problem.
Since designing breaking changes support might take some time, I would suggest this: publish the new major release under a different npm package name, and add this instead. What do you think?
@erquhart @lukeocodes
> Revert Algolia breaking changes

- plugins.json
**Test plan**
This is an update for issue Brikl/opensource#6 which patched and updated in Brikl/opensource#7
> chore: update netlify-plugin-next-dynamic to 1.0.9

- plugins.json
**Test plan**
https://app.netlify.com/sites/amazing-morse-5b1303/deploys/5ef12b6023223b0007c4284d
I only updated the typo that was reported here: https://github.com/soofka/netlify-plugin-chromium/issues/4
> Fixed typo in Chromium plugin description

- plugins.json
This PR adds [netlify-plugin-replace](https://github.com/ample/netlify-plugin-replace) to `plugins.json`. This build plugin replaces environment variables in the project's publish directory during the `onPostBuild` life-cycle event.
This PR replaces #128– thanks @ehmicky for the thoughtful suggestions! Appreciate your consideration :) 
**Test plan**
You can see a demo implementation [here](https://github.com/ample/netlify-plugin-replace-demo). The build logs are public and can be viewed [here](https://app.netlify.com/sites/netlify-plugin-replace-demo/deploys/5f4957037816aa0007cb879b).
> Add netlify-plugin-replace to plugins.json

- plugins.json
This plugin makes it easy for DebugBear customers to test each deployment and see how it affected page performance and Lighthouse scores.
**Test plan**
Deploy log: https://app.netlify.com/sites/mystifying-kilby-0e6399/deploys/5f4f59471ee5720008aeeded
---
I've considered using `utils.status.show()` to show the test result links, but it seems this still isn't supported on the Netlify website.
> Add netlify-build-plugin-debugbear

- plugins.json
Changed the plugin to use `onPostBuild` instead of `onSuccess`
**Test plan**
https://app.netlify.com/sites/nostalgic-hamilton-c4070a/deploys/5f510e5a127da60008fcb990
https://app.netlify.com/sites/nostalgic-hamilton-c4070a/deploys/5f511223c9b1bb0008a0db81
> fix: update netlify-plugin-is-website-vulnerable

- plugins.json
Changed the plugin to use `onPostBuild` instead of `onSuccess`
**Test plan**
https://app.netlify.com/sites/plugin-lighthouse/deploys/5f5127167ee09a0007295fb7
> fix: update netlify-plugin-lighthouse

- plugins.json
This [fixes](https://github.com/DebugBear/netlify-build-plugin-debugbear/commit/186a9c30162ac9e443fc235546a77c301d9b6fec) the [issue reported here](https://github.com/DebugBear/netlify-build-plugin-debugbear/issues/4), where API errors are reported as plugin errors.
**Test plan**
Run a test and provide an invalid API key.
> Update DebugBear plugin error handling

- plugins.json
This PR updates [netlify-plugin-replace](https://www.npmjs.com/package/@helloample/netlify-plugin-replace) to the latest version to correct an issue when the publish directory is included in the `.gitignore` file. 
When the publish directory is ignored, no replacements are made which can lead to some confusion as lots of SSGs follow this convention of not committing the build's output directory to revision control. Let me know if you have any questions. Thanks!
**Test plan**
The [demo application](https://github.com/ample/netlify-plugin-replace-demo) has been updated to reflect this new version. The latest build logs are accessible [here](https://app.netlify.com/sites/netlify-plugin-replace-demo/deploys/5f5a …
> Bump version of netlify-plugin-replace

- plugins.json
**Test plan**
- [fix: switch to failPlugin instead of failBuild](https://github.com/AshikNesin/netlify-plugin-pushover/pull/5) by @erezrokah
> Bump netlify-plugin-pushover version to v0.0.6

- plugins.json
Deactivating netlify-plugin-algolia-index because the [package is no longer maintained](https://github.com/lukeocodes/netlify-plugin-algolia-index#netlify-algolia-index-plugin). All new development has shifted to https://github.com/lukeocodes/netlify-plugin-algolia-export, which was submitted in https://github.com/netlify/plugins/pull/104.
**Test plan**
n/a
> Deactivate netlify-plugin-algolia-index

- plugins.json
**Test plan**
https://app.netlify.com/sites/algoliasearch-netlify/deploys/5f7dc0ec309e50000753d5c3
> fix: update algoliasearch-netlify to v0.0.14

- plugins.json
Includes a fix for https://github.com/netlify-labs/netlify-plugin-sitemap/issues/28
**Test plan**
https://app.netlify.com/sites/erez-build-reproductions/deploys/5f8588ffbcc71b000774226d
> fix: update sitemap plugin

- plugins.json
**Test plan**
Successful public deploy log: https://app.netlify.com/sites/netlify-plugin-image-optim-test/deploys/5f8878af609fb50cd4505d65. Unfortnately I need to find some unoptimised images to make this test repo more useful but for now you can see it running successfully and it matches the output from [`imagemin-app`](https://github.com/imagemin/imagemin-app) (see screenshot below).
> chore: bump image-optim version

- plugins.json
The updates include a new input named "buildEvent". Details can be viewed on https://github.com/bencao/netlify-plugin-inline-functions-env/blob/master/CHANGELOG.md.
**Test plans**
- With the new `exclude` flag: https://app.netlify.com/sites/bencao-test-netlify-env/deploys/5fa27bba25b696000800ef72
- With the new `include` flag: https://app.netlify.com/sites/bencao-test-netlify-env/deploys/5fa27a79e43634000735edbc
- With no `include` or `exclude` flags: https://app.netlify.com/sites/bencao-test-netlify-env/deploys/5fa27bf6274dca00070eb88d
Also unit test is introduced and included in https://github.com/bencao/netlify-plugin-inline-functions-env/blob/master/ …
> bump the version of netlify-plugin-inline-functions-env

- plugins.json
> fix: bump Next.js plugin to `1.0.1`

- plugins.json
**Test plan**
It's a minor update which checks if the build is run local. If so, it skip pinging the sitemaps.
> Update version  netlify-plugin-submit-sitemap

- Dockerfile
- README.md
- docs/CONTRIBUTING.md
- functions/npm-diff.js
- netlify.toml
- site/index.html
- site/plugins.json
Part of https://github.com/netlify/pod-the-builder/issues/106
This is publishing `plugins.json` to our CDN.
[Link to `plugins.json`](https://5fbffc01d0654600074c5cb8--netlify-plugins.netlify.app/plugins.json).
Once merged to `master`, this will be available at https://netlify-plugins.netlify.app/plugins.json
> feat: publish `plugins.json` to our CDN

- docs/CONTRIBUTING.md
- package.json
See background at https://github.com/netlify/build/pull/2076#discussion_r532657394
This publish the `plugins.json` to npm under the package name `@netlify/plugins-list`.
> Publish to npm

- netlify.toml
CORS is failing when fetching `plugins.json` (see @nasivuela comment [here](https://github.com/netlify/netlify-react-ui/pull/6408#pullrequestreview-542738474)).
This PR aims at fixing this.
> Fix CORS with plugins.json

- package.json
Fixes https://github.com/netlify/cli/issues/1616
This npm package supports any Node.js version since it only exports a JSON file at the moment.
I made the Node.js version match the one in Netlify Build.
> Fix Node.js version support

- .github/workflows/test.yml
- package-lock.json
- package.json
- test/main.js
Now that `plugins.json` is directly used in both our front-end and our build system, we should ensure its shape is valid to avoid any potential breakage.
This PR adds CI tests which check:
- All plugin attributes have a valid shape
- Each plugin package name is available in npm
- Each plugin package version is available in npm
- Each plugin repository URL is available
> Ensure `plugins.json` is always valid

- site/plugins.json
- Adds tag page support, behind a flag
- Adds author page support, behind a flag
- Fixes bug where "null" images were found in the content but couldn't be replaced
---
**Test plan**
https://app.netlify.com/sites/netlify-plugin-ghost-markdown-demo/deploys/5fd743754d5ec80e93395cf6
> Update netlify-plugin-ghost-markdown to 3.0.3

- site/plugins.json
**Test plan**
No plugins changes - just the repo link and author update
> fix(plugin-applitools): update repo link and author

- README.md
- docs/plugin_review.md
This adds guidelines on how to review plugins. This is primarily intended for Netlify reviewers, while `guidelines.md` is mostly intended for plugin authors.
@erezrokah Please share any feedback!
> Add plugin review guidelines

- docs/plugin_review.md
From context seems like a `not` was missing there :D let me know if that isn't the case 👍
> docs(review): missing `not` in process description

- site/plugins.json
See [changelog](https://github.com/netlify-labs/netlify-plugin-sitemap/releases/tag/v0.7.0)
**Test plan**
https://app.netlify.com/sites/erez-build-reproductions/deploys/600eddb9cf8cc50007747460
See https://600eddb9cf8cc50007747460--erez-build-reproductions.netlify.app/sitemap.xml that uses the value of `NETLIFY_PLUGIN_SITEMAP_BASEURL` env variable.
> feat(plugin-sitemap): update to version 0.7.0

- site/plugins.json
**Test plan**
First build: https://app.netlify.com/sites/matthewsimpson/deploys/60143c9e4b7b62048cbadf4a
Second build: https://app.netlify.com/sites/matthewsimpson/deploys/60143eb5a598010008f44965
The cache is stored in the first and restored in the second, which should improve Jekyll build times. It's probably less noticable on this site but I have other (private) sites that make use of image resizing that benefit greatly from this plugin (a 4m 30s build was reduced to 1m 15s).
> Add Jekyll Cache

- .github/workflows/release-please.yml
This adds `release-please` since this repository is published as a npm package.
Ideally, we'd want those PRs to be automatically merged, but I'm not sure whether there is an easy way to do it (without adding an additional GitHub action or app).
Note: an admin will need to add the `NODE_PKG_RELEASE_TOKEN` secret to this repository on GitHub.
> chore: add `release-please`

- package.json
This fixes tests timing out due to running many HTTP requests in parallel: https://github.com/netlify/plugins/runs/2042841869?check_suite_focus=true
Note: `got` itself does not [timeout by default](https://github.com/sindresorhus/got#timeout), so the timeout is only coming from Ava.
> chore: fix tests timeout

- site/plugins.json
**Test plan**
https://app.netlify.com/sites/erez-next-plugin-old/deploys/6050efb91a39b50007c8924a
> fix: update Next.js plugin compatibility to 1.1.2

- .github/workflows/release-please.yml
- docs/CONTRIBUTING.md
- package.json
This PR automates the `npm publish` part of the release.
> chore: automate npm publishing

- site/plugins.json
**Test plan**
The build: https://app.netlify.com/sites/monorepo-blog-1-yarn/deploys/605b79175695bc0008bfbf1b
And the actual sitemap produced containing the newly added feature in https://github.com/netlify-labs/netlify-plugin-sitemap/pull/70 - https://605b79175695bc0008bfbf1b--monorepo-blog-1-yarn.netlify.app/sitemap.xml - you can see the added prefix `/test-prefix`
> feat(sitemap): bump sitemap plugin to 0.8.0

- site/plugins.json
Thank you for your consideration 🐺
**Test plan**
This plugin is pretty lightweight - it calls the [QA Wolf](https://www.qawolf.com/) API to run end-to-end tests on Netlify deployments.
I have included some basic smoke tests in the [plugin itself](https://github.com/qawolf/netlify-plugin-qawolf) and more comprehensive tests in the [QA Wolf repo](https://github.com/qawolf/qawolf), where the API lives.
[Example project with this plugin](https://github.com/qawolf/netlify-plugin-example)
[Successful public deploy log](https://app.netlify.com/sites/netlify-plugin-qawolf-example/deploys/60639a20d105e7000882c69d)
[Follow up PR to update README with UI install …
> feat: add QA Wolf plugin

- .github/workflows/fossa.yml
- .github/workflows/release-please.yml
- .github/workflows/test.yml
- docs/PULL_REQUEST_TEMPLATE.md
- docs/plugin_review.md
PR to make the necessary changes in order to rename the default branch from `master` to `main`.
> chore: rename default branch from master to main

- site/plugins.json
This reverts the latest update of the Next.js plugin while the following bug is being looked at: https://github.com/netlify/netlify-plugin-nextjs/issues/254
> Revert "chore: upgrade essential next.js to 3.2.0"

- test/main.mjs
Fixes #297
The `compatibility` field was created to allow plugins to auto-upgrade breaking changes based on conditions such as Node.js version or Node modules versions. However, this will now also be used as part of versions pinning. In that new use case, no conditions is needed in the `compatibility` field, i.e. we should allow the items in that array have no conditions. At the moment, we validate against this.
> feat: allow `compatibility` entries without conditions

- site/plugins.json
**Test plan**
None needed. This is a cosmetic change. The name of the company is StepZen (not Stepzen). Sorry for the error.
> fix: Fix Camel case. Stepzen --> StepZen

- site/plugins.json
This PR upgrades `netlify-plugin-html-validate` to `1.0.0`.
#233 is currently ongoing to do the same. I opened a separate PR to do some testing on the `compatibility` approach and make sure this works correctly.
With this PR, new sites installing that plugin in the UI or in `netlify.toml` will use `1.0.0`, but existing sites with that plugin will keep using `0.1.1`. Sites using this plugin with `package.json` will also keep using the same version.
> feat: upgrade `netlify-plugin-html-validate` to `1.0.0`

- site/plugins.json
This adds a link to the breaking changes of `netlify-plugin-html-validate@v1` so users know how to fix their config.
> feat: add `migrationGuide` to `netlify-plugin-html-validate@v1`

- site/plugins.json
- test/main.mjs
As part of https://github.com/netlify/build/issues/2788, we now need to enforce that the first entry in the `compatibility` entry is the same as the `version` field.
While this requires a little more work for plugin authors, this has many pros outlined in the issue above.
Note: this should only be merged after https://github.com/netlify/build/pull/2791 is merged.
> feat: enforce that the first field in `compatibility` is the same as `version`

- docs/CONTRIBUTING.md
- docs/plugin_review.md
Fixes #236.
This adds some documentation about breaking changes in plugins.
Some implementation details are purposely omitted to only focus on the plugin author experience when updating a plugin.
> feat: add documentation about breaking changes in plugins

- site/plugins.json
- run tests after deploy `onSuccess` by default
- running tests `preBuild` and `postBuild` is opt-in
- using bundled-in Chromium browser by default, it is more stable than Electron
- tested across our example projects, see links https://github.com/cypress-io/netlify-plugin-cypress/pull/133
**Test plan**
> feat: update Cypress E2E plugin

- .github/workflows/release-please.yml
- .github/workflows/test.yml
Part of https://github.com/netlify/team-dev/issues/19
This runs the CI on the `latest` Node.js version.
> chore: run CI on latest Node.js

- site/plugins.json
**Test plan**
https://app.netlify.com/sites/netlify-plugin-hugo-cache-resources/deploys/60a66dcae06bd40007ea138e
Minor fix to log the actual cached file count.
> fix(plugin-hugo-cache-resources): log the actual cached file count

- site/plugins.json
The netlify plugin for Stepzen failed in some situations
because of a Node.js version dependency that was too recent.
This has been fixed in the latest version of the plugin.
This pull request updates the directory to use the latest version.
**Test plan**
This uses v1.0.2 plugin installed locally.
https://app.netlify.com/sites/jolly-clarke-e443a0/deploys/60a803f3f68da013509adfe4
> fix: Update version netlify-plugin-stepzen

- site/plugins.json
I am reverting the latest update because there have been some bugsnag events I'd liek to investigate, but it's late here
**Test plan**
> chore: revert essential next to 3.4.2

- .github/workflows/versioning.yml
Part of https://github.com/netlify/pod-workflow/issues/157
This PR adds versioning to `plugins.json`, based on @verythorough's [great idea](https://github.com/netlify/pod-workflow/issues/157#issuecomment-785201050).
Each time a new commit is pushed to `main`, a GitHub action updates the `v1` git branch so it points to `main` latest commit.
When a breaking change of `plugins.json` is made, we should change `v1` to `v2` in that GitHub action, and so on.
Consumers should then access `plugins.json` using https://v1--netlify-plugins.netlify.app/plugins.json instead of https://netlify-plugins.netlify.app/plugins.json
> feat: version `plugins.json`

- .github/workflows/versioning.yml
This fixes the GitHub action updating the `v1` branch, which [is currently failing](https://github.com/netlify/plugins/runs/3193749187?check_suite_focus=true)
> feat: fix `plugins.json` versioning

- .github/workflows/versioning.yml
This fixes the GitHub actions that updates the `v1` branch ([see error](https://github.com/netlify/plugins/runs/3194345135?check_suite_focus=true#step:3:8)).
> chore: fix `plugins.json` versioning

- .github/workflows/versioning.yml
Part of https://github.com/netlify/pod-workflow/issues/157
This switches `plugins.json` from using git branches to using git tags instead.
This git tags are named `list-v*`, not `v*`. This is because we already use `v*` as git tags for `@netlify/plugins-list` releases.
Also `v1` is already used as a branch name, and https://v1--netlify-plugins.netlify.app/plugins.json is already used by the front-end app in production now, and I want to lower the chance of breaking changes.
> chore: use git tags for `plugins.json` versioning

- docs/versioning.md
Part of https://github.com/netlify/pod-workflow/issues/157
This documents how the `plugins.json` syntax (not contents) is versioned.
> feat: document `plugins.json` syntax versioning

- .github/workflows/versioning.yml
- docs/versioning.md
Fixes #260.
Before `@netlify/build@17.4.0` ([PR](https://github.com/netlify/build/pull/3361)), adding new properties to the `compatibility` field in `plugins.json` would crash. `@netlify/build@17.4.0` was added to `netlify-cli@5.4.1`. 
In order to add new properties to the `compability` field, this PR bumps the `plugins.json` format version from v1 to v2.
Versions older than `@netlify/build@17.4.0` and `netlify-cli@5.4.1` use either https://netlify-plugins.netlify.app/plugins.json or https://list-v1--netlify-plugins.netlify.app/plugins.json. Since bumping to v2 will freeze the contents of https://list-v1--netlify-plugins.netlify.app/plugins.json, those older versions will keep working.
In other words, the only difference between v1 and v2 is that it adds a new requirement for consumers: …
> chore: bump `plugins.json` to v2

- docs/versioning.md
- index.js
- test/main.mjs
Implements @erezrokah feedback at https://github.com/netlify/plugins/pull/402#issuecomment-890860409
This exposes a `pluginsUrl` property to allow consumers to use npm versioning instead of updating the URL to version the `plugins.json` syntax. This only works if the consumer uses the npm package, not if the URL is fetched directly.
To avoid breaking consumers, this means any `plugins.json` breaking change will now also be a npm package breaking change.
This changes the npm package's return value, so this PR is a breaking change.
> chore!: expose `pluginsUrl`

- site/plugins.json
> fix: deprecate the old Gatsby cache plugin in description

- site/plugins.json
Description:
This plugin allows you to transfer environment variables in the runtime of your application from those declared in your netlify.toml file and which are only executed at build time.
You can even override variables defined in the Netlify UI!
---
**Test plan**
For test plan, see: [https://app.netlify.com/sites/use-env-in-runtime-plugin-demo/deploys/6106f295e858e60008be2c41](https://app.netlify.com/sites/use-env-in-runtime-plugin-demo/deploys/6106f295e858e60008be2c41)
> feat: add `netlify-plugin-use-env-in-runtime`

- docs/guidelines.md
Small fix of whitespaces in the plugins authoring guidelines.
> chore: fix indentation

- .github/workflows/release-please.yml
- .github/workflows/test.yml
**- Summary**
Related with https://github.com/netlify/team-dev/issues/31 - cache `npm cache` between workflow executions.
> chore(ci): cache npm cache dir between workflow execs

- site/plugins.json
Patch release 1.0.3 of the StepZen plugin unbreaks
a corner case where a misconfigured plugin environment
would could cause the build to fail rather than output
a helpful error message.
See: steprz/netlify-plugin-stepzen#17
> fix: corner case causing build internal error.

- site/plugins.json
Fixes https://github.com/netlify/pod-workflow/issues/294
[`netlify-plugin-search-index`](https://github.com/sw-yx/netlify-plugin-search-index) is using `zip-it-and-ship-it` directly which is creating some bugs and maintenance issues as outlined in https://github.com/netlify/pod-workflow/issues/294.
We've reached out in https://github.com/sw-yx/netlify-plugin-search-index/issues/31. However, the plugin does not [appear to be maintained anymore](https://github.com/sw-yx/netlify-plugin-search-index#future-plans). Following [our guidelines](https://github.com/netlify/plugins/blob/main/docs/guidelines.md#be-prepared-to-provide-support), this PR deactivates this plugin until this bug is fixed. 
Deactivating this plugin will hide it from the UI directory. Users will still be able to install it …
> fix: deactivate `netlify-plugin-search-index`

- .eslintrc.js
- .github/workflows/test.yml
- .prettierrc
- .prettierrc.json
- commitlint.config.js
- functions/npm-diff.js
- functions/utils/validate.js
- index.js
- package-lock.json
- package.json
- test/main.mjs
Fixes https://github.com/netlify/plugins/issues/365
This adds our shared linting and prettifying setup to this repository.
> chore: use `@netlify/eslint-config-node` setup

- package-lock.json
- package.json
This drops Node 8 support now that all consumers (Netlify CLI and Netlify Build) have dropped it.
> chore!: drop Node 8

- docs/guidelines.md
just updating a link in documentation
community-docs.netlify.com does not exist anymore, and we have moved over to forums
This should be non-impacting change
> chore: updating CoC

- package.json
The [main file is missing from the npm package](https://app.renovatebot.com/package-diff?name=@netlify%2fplugins-list&from=5.0.0&to=6.0.0) since https://github.com/netlify/plugins/pull/506
Thankfully, this was a major release, so this did not break programmatic consumers.
Our front-end is using the URL published by this repository's Netlify site, so it did not break it either. 
However, we should patch this.
The reason is: the `files` property in `package.json` usually includes the `main` property by default. However, it seems like this does not work when the `main` property starts with a dot. :man_shrugging: 
On the other hand, the `exports` property _must_ start with a dot, which I why I changed the `main` property so they are equal to each other. But that change broke the `files` …
> fix: main file is missing

- site/plugins.json
- [changelog](https://github.com/Tom-Bonnike/netlify-plugin-inline-critical-css/blob/master/CHANGELOG.md)
- [diff](https://github.com/Tom-Bonnike/netlify-plugin-inline-critical-css/compare/29b073b2f72d7b3b60c66ff7827230204a9a098e...d7c8143275b81d0433eea294fa5300f8d9a27165)
**Test plan**
https://app.netlify.com/sites/tombonnike/deploys/61b5fbfb7529a50008e2ce90
> feat: bump Inline Critical CSS to v2.0.0

- site/plugins.json
This adds a bug fix: https://github.com/netlify-labs/netlify-plugin-debug-cache/pull/12#event-5931062887
**Test plan**
Manual testing.
> fix: bump `netlify-plugin-debug-cache` to `1.0.4`

- site/plugins.json
**Test plan**
Fixes a parsing bug found here: https://github.com/tryfoobar/netlify-plugin-commandbar/pull/7
> fix: upgrade netlify-plugin-commandbar version to `0.0.4`

- site/plugins.json
I had the impression that `plugins.json` was deprecated so we did not bothered to update it. 
No breaking changes here, mostly dependencies upgrade.
> fix(plugins): update Algolia crawler

- site/plugins.json
This reverts commit 41408b8c2962ad034e98c5117c7d5ae3a66bbfa4.
The last update of the Algolia crawler plugin fails due to what seems to be a bug in our TypeScript setup.
**Test plan**
Not needed.
> Revert Algolia crawler latest update

- site/plugins.json
**Test plan**
Tested a deploy with a local instance of sentry and the deploy went just fine. My local version of the plugin was 1.1.1.
> feat: update version of @sentry/netlify-build-plugin

- site/plugins.json
A roll-up of dependency updates.
More info at https://github.com/steprz/netlify-plugin-stepzen/releases/tag/v1.0.4
**Test plan**
https://app.netlify.com/sites/romantic-khorana-08bd2e/deploys/622731c696238a0008387741
> fix: upgrade netlify-plugin-stepzen version to 1.0.4

- site/plugins.json
**Test plan**
Resolves the following issues:
- https://github.com/colbyfayock/netlify-plugin-cloudinary/issues/14
- https://github.com/colbyfayock/netlify-plugin-cloudinary/issues/15
Misc fixes / updates:
- Improved logging
- Adds warning for no images found in output (likely not configured the right path)
- Fixes bug where the `imagesPath` input wasn't being used
- Realized image output wouldn't be available prebuild 🤦‍♀️ which prevented uploads from working properly, moved this into build
Deploy with default settings: https://app.netlify.com/sites/glittery-cheesecake-01e8b9/deploys/623a1dde3cd3960008540958
Deploy with "upload" delivery type: https://app.netlify.com/sites/glittery-cheesecake-01e8b9/deploys/ …
> chore: updating netlify-plugin-cloudinary to 1.0.3

- site/plugins.json
This temporarily downgrades the auto-installed version of the Next.js plugin because of https://github.com/netlify/netlify-plugin-nextjs/issues/1287
The plugin version itself seems fine, but auto-installing it causes OOM errors.
> fix: downgrade Next to 4.2.8

- site/plugins.json
Rolling back due to missing polyfill
> fix: rollback to earlier version of Gatsby plugin

- site/plugins.json
**Test plan**
Test not needed.
This plugin was deprecated last year, and a deprecation message was added to the plugin description (https://github.com/netlify/plugins/pull/415). However, by deactivating the plugin, we can remove it from the directory for new installs. This will not remove the plugin from sites where it's already installed, and the plugin listing will still show in the list of installed plugins in the site admin UI.
Let me know if there's some reason why we shouldn't deactivate this!
> fix: deactivate the deprecated Gatsby Cache plugin

- site/plugins.json
Deprecates two Next.js plugins which are not needed and conflict with the official plugin
**Test plan**
> fix: deprecate old Next.js plugins

- site/plugins.json
This PR adds a prerelease version behind the feature flag `build_plugins_use_prerelease`. It also changes the name to "Next.js Runtime"
**Test plan**
> feat: add feature flagged version of Next runtime

- package-lock.json
- package.json
This unblocks an issue AVA has with Node.js 18. This will unblock #813 
**Test plan**
All tests should pass as no changes to plugins have been made.
See:
* https://github.com/nodejs/node/issues/44391
* https://github.com/avajs/ava/releases/tag/v4.3.3
> chore: update AVA to work with Node.js 18

- site/plugins.json
**TEST PLAN**
**Why `netlify-plugin-playwright-cache`**
When you install `playwright-chromium`, it downloads Chromium executables to a cache folder (not `node_modules`). Netlify does not cache this folder between builds, but caches `node_modules`. This leads to unsuccessful builds with the following error like this:
```
11:33:48 PM: [: Executable doesn't exist at /opt/buildhome/.cache/ms-playwright/chromium-1019/chrome-linux/chrome
╔═════════════════════════════════════════════════════════════════════════╗
11:33:48 PM: ║ Looks like Playwright Test or Playwright was just installed or updated. ║
11:33:48 PM: ║ Please run the following command to download …
```
> feat: add `netlify-plugin-playwright-cache`

- .github/workflows/sync-cms-to-repo.yml
- .gitignore
- bin/sync_cms_to_plugins_repo.js
Adds the stub of a GitHub action and script to sync CMS changes to the plugins repository. This is required so that I can ensure the dispatch of the action is working when the CMS Webhook runs.
A follow up PR will have the actual sync implemented.
Relates to:
- #820
- https://github.com/netlify/pod-ecosystem-frameworks/issues/223
**Test plan**
N/A
> chore: stub of GitHub action and script to sync CMS to plugins repo

- site/plugins.json
A Netlify plugin for Formspree!
See https://github.com/formspree/netlify-plugin-formspree
**Test plan**
Public deploy log: 
https://app.netlify.com/sites/formspree-example-netlify-plugin/deploys/633b377263c4ac24dcf06d98
This plugin just installs [formspree-cli](https://github.com/formspree/formspree-cli) and runs `formspree deploy`. The Formspree CLI can be tested by cloning it and running `npm run test`.
> feat: add netlify-plugin-formspree

- bin/utils.js
- test/bin/utils.js
- types/plugins.d.ts
Fixes an issue with the CMS to repo sync that caused builds to fail. Now the `_key` field of the compatibitlity array items is no longer included in the synched data.
**Test plan**
> fix: corrected sync issue from CMS that included _key in compatibility array items

- site/plugins.json
There were stuck builds in here that were closed to try to unblock the builds.
This PR manually updates `plugins.json` to match Sanity.
> chore: updates wording to match Sanity

- bin/utils.js
- test/bin/utils.js
Adding functionality to the Sanity -> Github plugin sync, decorating plugins with any defined environment variables
**Test plan**
> feat: support env vars in plugin definitions

- .github/workflows/sync-cms-to-repo.yml
- Use an auto-generated token to allow actions to run on PRs generated from Sanity changes
**Test plan**
> fix: use generated token for sanity to github plugin sync

- test/main.js
Update tests run in `build` to correctly handle variables introduced from Sanity sync
> fix: add variables to build step test

- site/plugins.json
Currently `build_plugins_use_prerelease` is targetting 10% of starter
**Test plan**
> feat: add feature-flagged version of Next runtime

- test/main.js
Fix for failing tests from plugins due to duplicate test titles
> fix: add packageName to variable tests

- .github/CODEOWNERS
Removing `@netlify/ecosystem-pod-frameworks` as a codeowner
> chore: remove frameworks team from codeowners

- .github/workflows/publish-workflow-ui.yml
- bin/publish_workflow_json.sh
- test/main.js
Add GitHub action to copy `workflow-ui.json` from supporting packages on changes to `plugins.json`
> feat: add github action to publish workflow ui files

- bin/utils.js
- test/main.js
Include plugin docs from Sanity, to enable a link to the documentation in the plugin installation flow.
> feat: add docs url to plugin model

- site/plugins.json
> fix: update Next.js to 4.29.3 behind flag

- site/plugins.json
> feat: latest version of gatsby plugin now requires v3 and up

- site/plugins.json
This reverts commit 8b739eae655348fbc7eca30196432b9b7729daf3.
Relates to #1113 
**Test plan**
> fix: Gatsby minimal version back to v3

- site/plugins.json
Version 3.5.2 of the Gatsby plugin should apply to Gatsby v2 and up 
**Test plan**
> Setting Gatsby version for featureflag

- site/plugins.json
This reverts commit 47304e56218336cb4cfc7289f7a5bd08e12758a2.
**Test plan**
> fix: Revert Gatsby featureFlag

- site/plugins.json
3.6.0 was being tested in staged rollout through previous week and now it's time to promote it
**Test plan**
> feat: remove prerelease feature flag, bump main to 3.6.0 for gatsby

- site/plugins.json
> feat: set next.js runtime 4.32.2 as stable version

- site/plugins.json
> feat: set next.js runtime 4.33.0 as stable version

- site/plugins.json
> feat: set next.js runtime 4.37.4 as stable version

- site/plugins.json
> feat: bump prerelease Next.js runtime to 4.38.1

- site/plugins.json
> feat: set next.js runtime 4.38.1 as stable version

- site/plugins.json
Enabling 4.39 behind feature flag (next-runtime)
> feat: add Next.js runtime 4.39.0 behind a feature flag

- site/plugins.json
**Test plan**
Set @netlify/plugin-nextjs 4.39.1 as stable and 4.39.2 in prerelease
> feat: set next.js runtime 4.39.1 stable and 4.39.2 in prerelease

- site/plugins.json
> feat: bump next.js runtime prerelease version to 4.39.3

- site/plugins.json
> feat: set next.js runtime 4.39.3 as stable version

- site/plugins.json
Updates Cloudinary  version to 1.10.2 to address a bug that uses the wrong Netlify URLs for deployed images.
The URL used now reflects:
```
let host = process.env.URL;
if ( process.env.CONTEXT === 'branch-deploy' || process.env.CONTEXT === 'deploy-preview' ) {
host = process.env.DEPLOY_PRIME_URL || ''
}
```
This unfortunately hasn't been tested in a prod-like environment beyond local development with `--context production` and using the Netlify Cloudinary project which builds with the latest plugin version by using the locally referenced version as I can't pin, but sounds like that will change with the new SDK for testing purposes.
> Update Cloudinary version

- site/plugins.json
> feat: set next.js runtime 4.40.2 as stable version

- site/plugins.json
> feat: set next.js runtime 4.41.2 as stable version

- site/plugins.json
> fix: update Next.js flagged version to 5.2.1

- site/plugins.json
> fix: update Next.js flagged version to 5.2.2

- site/plugins.json
> fix: bump @netlify/plugin-nextjs version

- site/plugins.json
See https://github.com/netlify/next-runtime/releases/tag/v5.5.0.
**Test plan**
> feat: bump @netlify/plugin-nextjs to 5.5.0

- site/plugins.json
Add a special IPX build of the next-runtime, behind a feature flag.
**Test plan**
@pieh tested it
> feat: add @netlify/plugin-nextjs@5.7.0-ipx.0

- site/plugins.json
> chore: bump next runtime to 5.10.1

- site/plugins.json
> chore: bump angular runtime to 2.3.1

- site/plugins.json
> chore: bump next runtime to 5.10.2

- site/plugins.json
> chore: bump next runtime to 5.10.6

- site/plugins.json
>  chore: bump next runtime to 5.10.7

- site/plugins.json
https://github.com/opennextjs/opennextjs-netlify/pull/2904
> fix: bump next-runtime to 5.11.1

- site/plugins.json
> fix: bump next-runtime to 5.11.2

- site/plugins.json
> fix: bump angular-runtime to 2.4.0

- site/plugins.json
Part of FRB-1807
**Test plan**
> fix: remove fully rolled out feature flag

- site/plugins.json
> fix: bump next-runtime to 5.11.5

- site/plugins.json
> fix: bump next-runtime to 5.11.6

- site/plugins.json
- test/main.js
> fix: bump next-runtime to 5.12.0

- site/plugins.json
> fix: bump next-runtime to 5.13.4

- site/plugins.json
> fix: bump next-runtime to 5.13.5
