plugins.json

add netlify-plugin-no-more-404

add netlify-plugin-no-more-404

---

plugins.json

We need consistent URLs for the repo field.

Remove README hashes

---

plugins.json

Shown in action at https://app.netlify.com/sites/netlify-plugin-cypress-example/deploys from https://github.com/cypress-io/netlify-plugin-cypress-example

Add netlify-plugin-cypress

---

README.md

rerun docs for Readme

---

README.md
plugins.json

In this PR I added Netlify Build Plugin for adding Chromium to Netlify CI/CD pipeline (https://github.com/soofka/netlify-plugin-chromium) to plugins.json file.

added netlify-plugin-chromium

---

README.md
plugins.json

Hi friends! This morning, I was auditing my [personal website](https://github.com/tom-bonnike/personal-website) with Lighthouse and ended up with a 99/100 performance score (😱) with the classic “inline your critical CSS” recommendation.
Since my personal website is a single .html file with no build step, I didn’t want to have to make it more complicated than it needs to be. I was hoping there would be a “post processing” asset optimization in the “Build & Deploy” settings of my site, but sadly there isn’t one at the moment.
I decided to create a plugin that other people could use, and now my website is a 100/100 and I can sleep soundly again!
You can browse the code and documentation here: https://github.com/Tom-Bonnike/netlify-plugin-inline-source, it relies on the `inline-source` …

Add Inline Source plugin

---

plugins.json

feat: add visual diff plugin

---

plugins.json

Lock versions for upcoming plugins install.

Lock initial versions.

---

plugins.json

Adds Sentry Netlify build plugin

Add sentry netlify build plugin

---

plugins.json

Updated the sentry netlify build plugin package name to the correct package on npm.

Updated the sentry netlify build plugin package name

---

README.md

Just wanted to update the README with all the new info. Hope that's ok.

runs npm run docs for readme update

---

plugins.json

First of all, thanks for building Netlify Build :) 
It is really awesome and provides limitless choice for anyone who wants to customize their build process 💯 
---
I wrote a plugin that would send real-time notifications to your Android, iPhone, iPad, and Desktop via Pushover.net after a successful/error build.
I would really appreciate any feedback/suggestions for this plugin. Thanks!

Add netlify-plugin-pushover

---

plugins.json

This upgrades `netlify-plugin-rss` to its latest version, which includes a bug fix.
@sw-yx

Upgrade the version of `netlify-plugin-rss`

---

plugins.json

Upgrade version of @sentry/netlify-build-plugin to 1.0.2

Upgrade version of @sentry/netlify-build-plugin

---

plugins.json

This upgrade `netlify-plugin-a11y` so that it does not have any more required inputs.
@sw-yx

Upgrade version of `netlify-plugin-a11y`

---

plugins.json

**Test plan**
Successful: https://app.netlify.com/sites/nostalgic-hamilton-c4070a/deploys/5ece7e7db612c600072f14c9
Failed: https://app.netlify.com/sites/nostalgic-hamilton-c4070a/deploys/5ece822626a1830008b529d9

feat: add netlify-plugin-is-website-vulnerable

---

docs/PULL_REQUEST_TEMPLATE.md

chore: fix pr template link

---

plugins.json

**Test plan**
https://app.netlify.com/sites/martinbean/deploys/5ecef99bfc40e5000720a3ea

Add AMP Server-Side Rendering plugin

---

plugins.json

**Successful build:**
https://app.netlify.com/sites/martinbean/deploys/5ecfc14b614af300069c7b77

Update AMP Server-Side Rendering plugin version

---

plugins.json

Fixes https://github.com/Munter/netlify-plugin-subfont/issues/32
**Test plan**

Update netlify-plugin-subfont to v5.0.3

---

plugins.json

https://diff.intrinsic.com/netlify-plugin-cypress/1.3.9/1.3.11
**Test plan**
Minimal changes: https://diff.intrinsic.com/netlify-plugin-cypress/1.3.9/1.3.11

Update netlify-plugin-cypress to 1.3.11

---

plugins.json

This version contains enhancement on how the 400 error messages are handled and notification sound for error message is changed to "siren" 
https://diff.intrinsic.com/netlify-plugin-pushover/0.0.4/0.0.5
**Test plan**
N/A

Bump netlify-plugin-pushover version

---

.github/workflows/fossa.yml

We have a `package.json` now 😄 
We can revert https://github.com/netlify/plugins/pull/66

chore: reintroduce fossa

---

plugins.json

**Test plan**
[https://app.netlify.com/sites/netlify-plugin-hugo-cache-resources/deploys/5ed647d1b8c25456eb52b70b](https://app.netlify.com/sites/netlify-plugin-hugo-cache-resources/deploys/5ed647d1b8c25456eb52b70b)

Add Hugo cache resources to netlify plugins

---

docs/PULL_REQUEST_TEMPLATE.md

This fixes a dead link in the PR template.

Fix link in PR template

---

plugins.json

- [X ] Adding a plugin
If updating a previously added package, create a diff at [diff.intrinsic.com](https://diff.intrinsic.com) and provide a link to the diff here.
Example link: https://diff.intrinsic.com/@netlify/plugin-sitemap/0.3.3/0.3.4
- [X ] Read and followed the [plugin author guidelines](/docs/guidelines.md).
- [ X] Included all [required fields](https://github.com/netlify/plugins/blob/master/docs/CONTRIBUTING.md#required-fields) in your entry.
- [ X] Tested the plugin [locally](https://docs.netlify.com/cli/get-started/#run-builds-locally) and [on Netlify](https://docs.netlify.com/configure-builds/build-plugins/#inst …

Add plugin netlify-purge-cloudflare-on-deploy

---

plugins.json

**Test plan**
https://app.netlify.com/sites/netlify-plugin-submit-sitemap/deploys/5ed72acda7c8231e23f5c8a4

Add netlify-plugin-submit-sitemap

---

plugins.json

**Test plan**
Deploy log (scroll to the end):
https://app.netlify.com/sites/elastic-easley-4ab11f/deploys/5ee10492a9297824743c7210

feat: add lighthouse plugin

---

plugins.json

Add a new plugin for inlining build time environment variables into netlify functions
**Test plan**
With Verbose Flag (Good For Debugging)
https://app.netlify.com/sites/bencao-test-netlify-env/deploys/5ee08d410447940007227992
Without Verbose Flag (Default Behavior with no Inputs)
https://app.netlify.com/sites/bencao-test-netlify-env/deploys/5ee08efdc1547e000860811c
The plugin transforms function files, and it works well with `netlify-plugin-contextual-env`.
Given the following ENV settings in Netlify
Input
```
async function handler(event, context) {
return {
statusCode: 200,
body: JSON.stringify({
BENBEN: process.env.BENBEN,
CONTEXT: process.env.CONTEXT,
HAY_TEST: process.env.HAY_TEST,
BUILD_ID: …
```

add netlify-plugin-inline-functions-env

---

plugins.json

**Test plan**
https://app.netlify.com/sites/elastic-easley-4ab11f/deploys/5ee26c563c974a00072b056f

feat: update lighthouse plugin

---

docs/PULL_REQUEST_TEMPLATE.md

Fix type in PR template

---

plugins.json

Intrinsic DIFF isn't working? Heres my diff: https://github.com/lukeocodes/netlify-plugin-algolia-index/commit/0669e3b5dab7008ac8c4ad17a3c4e5c082ac2571
Previous versions just created JSON, didn't export directly to Algolia. This now exports directly to Algolia. Uses deploy environment variables.
**Test plan**
Add plugin, setup environment variables (as per README.md), build site.
Deploy log from deploy on netlify: https://pastebin.com/M0dhERU7

v1 released - Export directly to Algolia from postBuild

---

plugins.json

**Test plan**
https://app.netlify.com/sites/eloquent-meitner-866f41/deploys/5f07d2a43ea710000730ab2d

Add netlify-build-plugin-perfbeacon

---

plugins.json

Only updating the plugin's description.

update netlify-plugin-submit-sitemap description

---

plugins.json

Added Cloudflare API Token Authentication Support
**Test plan**
**API Token Authentication (positive test):** [https://app.netlify.com/sites/dev-duvee-digital/deploys/5f14545b903031be1cc87c67](https://app.netlify.com/sites/dev-duvee-digital/deploys/5f14545b903031be1cc87c67)
**API Key Authentication (positive test):** [https://app.netlify.com/sites/dev-duvee-digital/deploys/5f1451df721839000719238e](https://app.netlify.com/sites/dev-duvee-digital/deploys/5f1451df721839000719238e)
**Invalid Environment Variables (negative test):** [https://app.netlify.com/sites/dev-duvee-digital/deploys/5f1453711561750007d5f166](https://app.netlify.com/sites/dev-duvee-digi …

feat: update netlify-purge-cloudflare-on-deploy

---

plugins.json

tested locally w/ `netlify build`, working as expected
**Test plan**

feat: update netlify-plugin-gridsome-cache plugin

---

plugins.json

This version adds detailed reporting on which audits caused a category to fail
**Test plan**
On success: https://app.netlify.com/sites/plugin-lighthouse/deploys/5f1877277ad0800007662ce4
On error: https://app.netlify.com/sites/plugin-lighthouse/deploys/5f184ada44438d0008132480

feat(plugin-lighthouse): update to version 1.4.0

---

plugins.json

**Test plan**
https://app.netlify.com/sites/netlify-plugin-submit-sitemap/deploys/5f22ded0658a5d00081e38e0

chore:  update netlify-plugin-submit-sitemap 0.2.2

---

plugins.json

**Test plan**
This is a workaround fix for https://github.com/netlify/build/issues/1411
Test with resources: https://app.netlify.com/sites/netlify-plugin-hugo-cache-resources/deploys/5f3e71d04649a000070f3e94
Test without resources: https://app.netlify.com/sites/netlify-plugin-hugo-cache-resources/deploys/5f3e7293aaedc7000727ca64

update netlify-plugin-hugo-cache-resources 0.1.5

---

plugins.json

**Test plan**
Remove previous workaround as discussed here https://github.com/netlify/build/issues/1411
With resources: https://app.netlify.com/sites/netlify-plugin-hugo-cache-resources/deploys/5f47a172033b2c0008f7cc99
Without resources: https://app.netlify.com/sites/netlify-plugin-hugo-cache-resources/deploys/5f47a18b67f73a000770995c

Update netlify-plugin-hugo-cache-resources v0.1.6

---

plugins.json

Version bumped to reflect updated manifest.yml & I cleaned up the description & author values. Thanks!
**Test plan**
A build with the latest version is [here](https://app.netlify.com/sites/netlify-plugin-replace-demo/deploys/5f4994ea98d2860008ab1244).

Update plugins.json to reflect new version of netlify-plugin-replace

---

plugins.json

Follow up on https://github.com/chrism2671/netlify-purge-cloudflare-on-deploy/pull/9
**Test plan**
- With env variables configured: https://app.netlify.com/sites/friendly-fermat-d052d6/deploys/5f575a08228a5000087f6d43
- With missing env variables: https://app.netlify.com/sites/friendly-fermat-d052d6/deploys/5f575ac7080cf006d562f71a

feat: update netlify-purge-cloudflare-on-deploy plugin

---

plugins.json

- [z] Updating a plugin
**Test plan**
Just a small update to the plugin description (matching change on `package.json` in the [upstream repository](https://github.com/erezrokah/netlify-plugin-is-website-vulnerable/pull/49)) to make the plugin better discoverable in the directory.

fix: update plugin description to easily find the plugin

---

plugins.json

A small update to the Lighthouse plugin to better report JSON parsing errors
**Test plan**

fix: update lighthouse plugin

---

plugins.json

This plugin adds security insights via scans and monitoring of JavaScript libraries in a build for a website as well as monitors it on the Snyk platform.
**Test plan**
Release and deploy: https://github.com/snyk-labs/netlify-plugin-snyk/actions/runs/247805238

Add netlify-plugin-snyk

---

plugins.json

Updating the plugin name for a friendlier naming convention :-)
**Test plan**
Not required.

Updating the Snyk plugin name to be friendlier

---

plugins.json

fix: upgrade netlify-plugin-html-minify

---

plugins.json

Bumping the version of the Netlify plugin so we can track test usage from Snyk.

Update plugin version

---

plugins.json

Adds https://github.com/netlify-labs/netlify-plugin-sitemap/pull/13 and https://github.com/netlify-labs/netlify-plugin-sitemap/pull/25
**Test plan**
https://app.netlify.com/sites/determined-johnson-c85a62/deploys/5f79e92652f7910007efc97f
https://5f79e92652f7910007efc97f--determined-johnson-c85a62.netlify.app/sitemap.xml

feat: update sitemap plugin

---

plugins.json

**Test plan**
https://app.netlify.com/sites/cranky-mcnulty-5ab308/deploys/5f7510ed12c3482dd2bbf317

Add Nimbella plugin

---

plugins.json

**Test plan**
https://app.netlify.com/sites/algoliasearch-netlify/deploys/5f790fd490d5ab0007d19d54

feat(plugin): add official Algolia plugin

---

docs/CONTRIBUTING.md

This adds some documentation about releasing the Build plugins list.

Add documentation about releasing

---

plugins.json

- [x ] Read and followed the [plugin author guidelines](https://github.com/netlify/plugins/blob/master/docs/guidelines.md).
**Test plan**
https://app.netlify.com/sites/deepabstractart/deploys/5f920a9ccced07000816a96a

Add netlify-plugin-pagewatch

---

plugins.json

**Context**
Adding this plugin to the list for a smoother installation experience. Because the plugin requires some additional configuration for now, we intend to hide it from the UI list until that config is no longer needed. Because of this, https://github.com/netlify/netlify-react-ui/pull/6099 must be merged before merging this PR.
cc @lindsaylevine @ehmicky @nasivuela

Add netlify-plugin-nextjs

---

plugins.json

--- 
- Changelog https://github.com/algolia/algoliasearch-netlify/blob/master/CHANGELOG.md
All previous version were frontend related.

fix: update @algolia/netlify-plugin-crawler

---

plugins.json

**Test plan**
Tested on a private repo so pasting the build log below. 
```
10:36:53 PM: Build ready to start
10:36:54 PM: build-image version: 253f72909528f25a82c4640ca58f2e974d52abd9
10:36:54 PM: build-image tag: v3.4.4
10:36:54 PM: buildbot version: 9319377401b48c5db16b3a7910b25af0524f548a
10:36:55 PM: Fetching cached dependencies
10:36:55 PM: Starting to download cache of 136.7MB
10:36:57 PM: Finished downloading cache in 1.888309712s
10:36:57 PM: Starting to extract cache
10:37:01 PM: Finished …
```

Update version of netlify-plugin-nimbella

---

plugins.json

update @netlify/plugin-nextjs to v1.0.0

---

plugins.json

fix: bump plugin-nextjs version to 1.0.2

---

site/plugins.json

**Test plan**
https://app.netlify.com/sites/erez-build-reproductions/deploys/5fd0b2420f7bd6de97a02c2c

fix: update sitemap plugin

---

site/plugins.json

**Test plan**
- Public build: https://app.netlify.com/sites/algoliasearch-netlify/deploys/5fd0c1a944ae86f07d33ddfe
- Changelog: https://github.com/algolia/algoliasearch-netlify/blob/master/CHANGELOG.md
Mostly concern UI changes and mark the end of the initial roadmap we had set

fix(algolia): release v1

---

docs/CONTRIBUTING.md

This updates the releasing documentation with the latest information.

Improve releasing documentation

---

site/plugins.json

bump nextjs-plugin version to 1.0.3

---

site/plugins.json

**Test plan**
Adds an input option to specify the relative path to the source directory in case it's using Hugo's "--s" option. Use case discussed in https://github.com/cdeleeuwe/netlify-plugin-hugo-cache-resources/issues/5
**input.srcdir = not specified**
Looks for "resources" folder
log: https://app.netlify.com/sites/netlify-plugin-hugo-cache-resources/deploys/5fdd995979f8890008926e96
**input.srcdir = path/to/website**
Looks for "path/to/website/resources" folder
log: https://app.netlify.com/sites/netlify-plugin-hugo-cache-resources/deploys/5fdd9611165aa400070f6a84

Update netlify-plugin-hugo-cache-resources 0.2.0

---

site/plugins.json

Updating the description with wording by @MelanieCrissey 
**Test plan**
N/A - wording change only

Update description for @netlify/plugin-nextjs

---

site/plugins.json

**Test plan**
https://app.netlify.com/sites/erez-build-reproductions/deploys/5fe1e88edd6f02000787c87a

feat(plugin-sitemap): update sitemap plugin to support a custom path

---

site/plugins.json

**Test plan**
https://app.netlify.com/sites/eloquent-mahavira-7bb325/deploys/5ff4723c8cb84300b2b5c02f

fix(plugin-sitemap): update to version 0.6.2

---

site/plugins.json

bump next on netlify plugin version to 1.0.4

---

site/plugins.json

bump nextjs plugin version to 1.0.5

---

.github/CODEOWNERS

Please let me know if I got the ownership wrong. @erquhart @verythorough

Set `CODEOWNERS`

---

site/plugins.json

bump nextjs plugin to 1.0.6

---

site/plugins.json

bump next plugin to 1.0.7

---

site/plugins.json

bump next on netlify version to 1.0.8

---

docs/CONTRIBUTING.md
package-lock.json
package.json
site/plugins.json
test/main.js

Fixes https://github.com/netlify/plugins/issues/208
Keeping this open as a draft to get visibility as we probably want to tell plugin authors before/if we merge this.

feat: enforce consistent plugins names

---

site/plugins.json

bump nextjs plugin to v1.1.0

---

site/plugins.json

- [✓] Adding a plugin
- [✓] Read and followed the [plugin author guidelines](https://github.com/netlify/plugins/blob/master/docs/guidelines.md).
- [✓] Included all [required fields](https://github.com/netlify/plugins/blob/master/docs/CONTRIBUTING.md#required-fields) in your entry.
- [✓] Tested the plugin [locally](https://docs.netlify.com/cli/get-started/#run-builds-locally) and [on Netlify](https://docs.netlify.com/configure-builds/build-plugins/#install-a-plugin), using the plugin version stated in your entry.
**Test plan**
Please add a link to a successful public deploy log using the stated version of the plugin. Include any other context reviewers …

Added a JavaScript Obfuscator Netlify build plugin

---

site/plugins.json

Rebasing @racoonx2p work. Pulled from #195

feat: add gmail plugin

---

site/plugins.json

**Test plan**
https://app.netlify.com/sites/tombonnike/deploys/6019316d6c650c00075cbda2

Bump netlify-plugin-inline-critical-css to 1.2.0

---

site/plugins.json

bump next plugin version to v1.1.1

---

site/plugins.json

Updated the description and name for `JavaScript Obfuscator` as well as `Jekyll cache` name

fix(plugins): updated js obfuscator name and description and jekyll name correction

---

site/plugins.json

feat: upgrade Next.js plugin to `2.0.0`

---

site/plugins.json

**Test plan**
I bumped the plugin to v1.9.2 in the following repos, all successfully built and deployed to Netlify
- https://github.com/cypress-io/netlify-plugin-cypress-example
- https://github.com/cypress-io/netlify-plugin-prebuild-example
- https://github.com/bahmutov/eleventyone
- https://github.com/bahmutov/gatsby-starter-portfolio-cara

Update netlify-plugin-cypress to the latest version

---

site/plugins.json

Update netlify-plugin-minify-html to 0.3.1

---

site/plugins.json

upgrade nextjs plugin to 2.0.1

---

site/plugins.json

**Test plan**
https://app.netlify.com/sites/unruffled-goodall-33e532/deploys/602c52a96ce2a32f0cdf114b

Update Nimbella plugins version.

---

package-lock.json
package.json
test/main.js

This fixes tests to both allow and validate the new `compatibility` field.

feat: allow and validate `compatibility` field

---

site/plugins.json

https://github.com/netlify-labs/netlify-plugin-lighthouse/releases/tag/v1.4.3

chore: upgrade Lighthouse plugin

---

site/plugins.json

chore: upgrade Lighthouse plugin with `compatibility` field

---

renovate.json5

This adds Renovate.
This automatically merges Renovate PRs.

chore: add Renovate

---

site/plugins.json

See https://github.com/netlify/next-on-netlify-enterprise/issues/16#issuecomment-791541482

feat: support Next <10.0.6 users with Essential Next.js plugin

---

site/plugins.json

**Test plan**
https://app.netlify.com/sites/lukeb-co-uk/deploys/60393a3a651aff0007f0f7a7

Add webmentions plugin

---

site/plugins.json

bump Essential Next.js version to 3.0.0

---

site/plugins.json

fix: Essential Next.js 3.0.1

---

site/plugins.json

fix: revert Essential Next.js 3.0.0

---

site/plugins.json

fix: upgrade Essential Next.js `3.0.3`

---

site/plugins.json

This backports some improvements for Next 9 users.

fix: upgrade Essential Next.js to `1.1.3`

---

site/plugins.json

**Test plan**
My [update](https://github.com/qawolf/netlify-plugin-qawolf/commit/f4277da131077c0e2f387aaee5ef2d8ca39f5355) just includes the timestamp of the current commit in the API request to QA Wolf. A successful run is visible [here](https://app.netlify.com/sites/netlify-plugin-qawolf-example/deploys/607a1de188aa350007e97454).

chore: update QA Wolf plugin

---

README.md

Applied the wrong type to the #276 PR 😬

feat(qa-wolf): force latest package release #276

---

README.md

chore(docs): cleanup extra space introduced in #278

---

site/plugins.json

**Test plan**
Tested new changes, deploy successful

feat: update version of @sentry/netlify-build-plugin

---

site/plugins.json

This lets users publish the Lighthouse report to their site.
See https://github.com/netlify-labs/netlify-plugin-lighthouse/releases/tag/v2.1.0 
**Test plan**
https://app.netlify.com/sites/erez-build-reproductions/deploys/60801b7a099fb90008539473
https://chore-test-lighthouse--erez-build-reproductions.netlify.app/reports/lighthouse.html

feat(plugin-lighthouse): update to version 2.1.0

---

site/plugins.json

feat: upgrade essential next.js to 3.2.0

---

site/plugins.json

**Test plan**
https://app.netlify.com/sites/simpixelated/deploys/6082fd41ec751b7a69691f2e - for your own testing you will need a free [Ghost Inspector account](https://app.ghostinspector.com/account/create) and create a least one suite + test.

feat: add Ghost Inspector Netlify plugin

---

site/plugins.json

upgrade essential next.js to 3.2.1

---

site/plugins.json

chore: upgrade essential next.js to 3.2.2

---

package.json
test/main.mjs

chore: simplify test

---

site/plugins.json

chore: bump v1 essential nextjs plugin to v1.1.4

---

site/plugins.json

**Test plan**
https://app.netlify.com/sites/pedantic-tesla-a2d422/deploys/60978ba180c8561836aa04ee

feat: Add Airbrake Netlify plugin

---

site/plugins.json

Implements https://github.com/netlify/plugins/pull/317#discussion_r631102503

chore: fix HTML validate plugin migration URL

---

site/plugins.json

chore: update essential nextjs to 3.3.0

---

site/plugins.json

**Test plan**
Successful public deploy: https://app.netlify.com/sites/arnaudligny/deploys/609a6e1ac7dc230007105eca.

feat: add Cecil cache

---

site/plugins.json

**Test plan**
https://app.netlify.com/teams/peter-muller/builds/609e48b3552dd60007d7aea9
```
11:53:55 AM: Waiting for other deploys from your team to complete
11:55:04 AM: Build ready to start
11:55:06 AM: build-image version: 0582042f4fc261adc7bd8333f34884959c577302
11:55:06 AM: build-image tag: v3.7.6
11:55:06 AM: buildbot version: ffdb264c3e1df7cdeec37fab1a0fdc9b6d6b8f73
11:55:06 AM: Fetching cached dependencies
11:55:06 AM: Starting to download cache of 302.0MB
11:55:13 AM: Finished downloading cache …
```

Bump netlify-plugin-subfont version to v6

---

site/plugins.json

chore: update essential nextjs to 3.3.1

---

site/plugins.json

chore: upgrade essential next.js to 3.4.0

---

site/plugins.json

Revert "chore: upgrade essential next.js to 3.4.0"

---

site/plugins.json

chore: upgrade essential next.js to 3.4.1

---

site/plugins.json

Reverts netlify/plugins#341
pain

Revert "chore: upgrade essential next.js to 3.4.1"

---

site/plugins.json

chore: upgrade nextjs to 3.4.2

---

site/plugins.json

**Test plan**
Bumping to latest version to address latest enhancements
Please refer to https://github.com/AshikNesin/netlify-plugin-pushover/pull/8 for more context
FYI: https://app.netlify.com/sites/nervous-goodall-20edf6/deploys/60bccbe9c4952e0009320c1e

feat: bump netlify-plugin-pushover to 0.1.1 for enhancements

---

site/plugins.json

**Notable changes**
- Replace `http-server` with `express` to support compression via https://github.com/netlify-labs/netlify-plugin-lighthouse/pull/222, kudos to @griable
- Puppeteer v10 (Chromium 92.0.4512.0 (r884014)) via https://github.com/netlify-labs/netlify-plugin-lighthouse/pull/217
- Lighthouse v8 (Treemap support) via https://github.com/netlify-labs/netlify-plugin-lighthouse/pull/216
**Test plan**
https://app.netlify.com/sites/netlify-build-reproductions/deploys/60c600c3ee6ca3712a90b59e

fix(plugin-lighthouse): update to version 2.1.2

---

site/plugins.json

**Test plan**
[Link is here](https://app.netlify.com/sites/zen-torvalds-8e5c2a/deploys/60cab0940b7e3c00089a2208)! Thank you 🐺

feat(qawolf): bump qawolf to 1.2.0

---

site/plugins.json

feat(plugin-gatsby): add Essential Gatsby plugin

---

site/plugins.json

chore: upgrade essential next to 3.5.0

---

site/plugins.json

feat: update @netlify/plugin-nextjs to 3.6.2

---

site/plugins.json

fix: update next plugin to 3.6.3

---

site/plugins.json

fix: upgrade Next plugin to 3.7.0

---

site/plugins.json

fix: upgrade Next.js plugin to 3.7.1

---

.github/workflows/versioning.yml

This GitHub action name is wrong.

chore: fix GitHub action name

---

package.json

This fixes the package's main entry point.

fix: main entry point

---

site/plugins.json

feat: update Next to 3.8.0

---

test/main.mjs

Part of https://github.com/netlify/pod-workflow/issues/243
This adds a `featureFlag` property to the `compatibility` field.

feat: add `featureFlag` property

---

site/plugins.json

feat: add essential angular universal beta

---

site/plugins.json

**Test plan**
This was requested by @MelanieCrissey. I wasn't sure if this needed a version bump or not 🤔

chore: remove "Essential" from name of Angular plugin

---

docs/plugin_review.md

Fixes https://github.com/netlify/plugins/issues/343
This adds more guidelines on how to properly use `netlifyConfig` inside plugins.

feat: guidelines for proper `netlifyConfig` usage

---

site/plugins.json

feat: update essential next to 3.9.0

---

site/plugins.json

feat: update angular universal plugin to 1.0.1

---

functions/npm-diff.js

This is a small refactoring of a function.

chore: refactor `getNewPluginsUrls()`

---

functions/npm-diff.js

Small refactoring of some logic related to printing diff URLs.

chore: refactor diff URLs printing

---

functions/npm-diff.js

Small refactoring of HTTP requests logic.

chore: refactor HTTP requests

---

functions/npm-diff.js

This is a small refactoring of the main handling logic.

chore: refactor main handling logic

---

functions/npm-diff/compute.js

This refactors some logic related to the plugins diff.

chore: refactor plugins diff

---

functions/npm-diff/index.js
functions/npm-diff/validate.js

This refactors the validation logic.

chore: refactor validation

---

site/plugins.json

fix: update Next plugin to 3.9.2

---

site/plugins.json

fix: deactivate this gmail plugin

---

site/plugins.json

feat: add simple build logger plugin

---

.gitignore
site/plugins.json

Updating to version 4. I've included a shortlink for release notes. 
**Test plan**

feat: upgrade Next plugin to 4.0.0

---

.gitignore
package-lock.json
package.json

chore(deps): switch to c8, remove unneeded devDependencies

---

site/plugins.json

fix: Update Next plugin to 4.1.1

---

site/plugins.json

fix: update to Next 4.2.1

---

site/plugins.json

This update includes various dependencies updates, and drops support for Node.js 10
See https://github.com/erezrokah/netlify-plugin-is-website-vulnerable/releases/tag/v2.0.0 and https://github.com/erezrokah/netlify-plugin-is-website-vulnerable/releases/tag/v2.0.1
**Test plan**
Failed deployed due to vulnerabilities https://app.netlify.com/sites/netlify-plugin-is-website-vulnerable/deploys/61f29253180c220007d96a7c
Successful deploy https://app.netlify.com/sites/netlify-plugin-is-website-vulnerable/deploys/61f3a8d69473310008e52173

feat: update plugin netlify-plugin-is-website-vulnerable to version 2.0.1

---

site/plugins.json

fix: update Next plugin to 4.2.2

---

site/plugins.json

feat: upgrade skip nx plugin to 0.0.5

---

site/plugins.json

feat: upgrade Gatsby plugin to v2

---

renovate.json5

Part of https://github.com/netlify/team-dev/issues/36
This uses our new Renovate configuration specific for repositories which have migrated to pure ES modules.
---
For us to review and ship your PR efficiently, please perform the following steps:
🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re
fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
passes our tests.

chore: use ESM-specific ESLint configuration

---

site/plugins.json

Release https://github.com/erezrokah/netlify-plugin-is-website-vulnerable/releases/tag/v2.0.2
**Test plan**
Build log https://app.netlify.com/sites/netlify-plugin-is-website-vulnerable/deploys/6200ef1c5587e100086fde1e

feat: update plugin netlify-plugin-is-website-vulnerable to version 2.0.2

---

site/plugins.json

**Test plan**
https://gist.github.com/aaronbassett/f19ec43e6da0e9c69c00c932c4ae0d32

feat: add New Relic plugin

---

site/plugins.json

For submission/review! 🔍  ⚡
**Test plan**

feat: plugin Submission: CommandBar + Netlify

---

site/plugins.json

 feat: update plugin @netlify/plugin-nextjs to version 4.2.7

---

site/plugins.json

feat: upgrade Lighthouse plugin to `2.1.3`

---

site/plugins.json

fix: update Gatsby plugin to 2.0.3

---

site/plugins.json

**Test plan**
Installation instructions are up to date on the main README: https://github.com/colbyfayock/netlify-plugin-cloudinary
PR with Netlify UI instructions is ready to merge: https://github.com/colbyfayock/netlify-plugin-cloudinary/pull/13
Recent deploy logs: https://app.netlify.com/sites/netlify-plugin-cloudinary/deploys/6217eefdadc3d600080bc2cc

Add Cloudinary plugin

---

site/plugins.json

feat: update plugin netlify-plugin-is-website-vulnerable to version 2.0.3

---

site/plugins.json

feat: update Gatsby to 2.1.1

---

site/plugins.json

fix: update Gatsby to 2.1.2

---

site/plugins.json

fix: update Next plugin to 4.3.1

---

site/plugins.json
test/main.js

Adds a feature flag for the latest version of the Next plugin

chore: add feature flag for Next plugin

---

site/plugins.json

feat: update plugin @netlify/plugin-gatsby to version 3.0.0

---

site/plugins.json

feat: update Next plugin to 4.4.2

---

site/plugins.json

feat: update plugin @netlify/plugin-nextjs to version 4.7.0

---

site/plugins.json

Hello Netlify team 🙌 
This is the first version of the Very Good Security plugin. It lets you update VGS routes at the same time as your site deployments. Without this plugin, you would need to manually update VGS routes via UI/CLI or set up a separate CI pipeline.
**Test plan**
To test the plugin, please follow README in the [repo](https://github.com/verygoodsecurity/netlify-plugin-vgs) or try [example project](https://github.com/verygoodsecurity/netlify-plugin-example)

feat: add Very Good Security plugin

---

site/plugins.json

**Test plan**
- [Sign up](https://app.takeshape.io/signup) for an account on TakeShape and follow the instructions in the plugin [README](https://github.com/takeshape/netlify-plugin-takeshape/blob/main/README.md).
- Successful deploy log: https://app.netlify.com/sites/mellow-kataifi-2c1043/deploys/627d3b3fd7b0cb000930ba92

feat: add TakeShape plugin

---

site/plugins.json

feat: downgrade next plugin because of bug

---

site/plugins.json

**Test plan**
https://app.netlify.com/sites/flutter-plugin/deploys/62601825c3a1f70008d0c006

feat: add plugin netlify-plugin-flutter at version 1.1.0

---

site/plugins.json

feat: update netlify-plugin-nx-skip-build to v0.0.7n

---

site/plugins.json

fix: revert plugin @netlify/plugin-nextjs to version 4.9.3

---

site/plugins.json

feat: update lighthouse plugin to v3.0.1

---

site/plugins.json

feat: update plugin @netlify/plugin-gatsby to version 3.3.1

---

site/plugins.json

feat: remove feature flag for next runtime v18

---

site/plugins.json

feat: update plugin @netlify/next-runtime to version 4.19.0

---

site/plugins.json

feat: upgrade next runtime version

---

.gitignore
site/plugins.json

Adding a plugin to test new displaypreferences option
**Test plan**
No manual testing of the plugin needed.

feat: testing display preferences for plugins

---

site/plugins.json

**Test plan**
Please add a link to a successful public deploy log using the stated version of the plugin. Include any other context reviewers might need for testing. https://app.netlify.com/sites/netlify-plugin-ghost-markdown-demo/deploys/630490577d2b184655b30fa6
Ps. Has the local development workflow improved for Build Plugins? I currently have an additional repo which is connected to a Netlify site just to test my plugin locally. Ideally I'd have a test / demo directory in my Build Plugin repo which I can test with and demonstrate the plugin. Can anyone give me any pointers? Thanks!

feat: update `netlify-plugin-ghost-markdown` to v3.1.0

---

.github/workflows/sync-cms-to-repo.yml
bin/sync_cms_to_plugins_repo.js
bin/sync_cms_to_repo.sh
bin/utils.js
package-lock.json
package.json
test/bin/utils.js
types/plugins.d.ts

Synchronizes data coming from our CMS via a Webhook to the plugins repo that dispatches a GitHub action. 
Steps the action performs:
- Creates and switches to a new branch with the following naming convention, "`sync_cms_to_plugins_{date in milliseconds}"`
- Updates site/plugins.json and commits it to the branch
- Creates a pull request with the title `"chore: cms to repo sync"` and two labels: `cms_sync` and `automerge`
- Assuming the PR passes all checks, it merges automatically
- Relates to #820 
- Closes https://github.com/netlify/pod-ecosystem-frameworks/issues/223
**Test plan**
Please add a link to a successful public deploy log using the stated version of the plugin. Include any other context …

feat: added synchronization from CMS to repo

---

site/plugins.json

**Test plan**
1. Build log without cache: https://app.netlify.com/sites/arnaudligny/deploys/633ae088b233ee178e294210
2. Build log with cache: https://app.netlify.com/sites/arnaudligny/deploys/633ae1d1cdd2420f2ce74c46

feat: update version of Cecil cache

---

bin/sync_cms_to_plugins_repo.js
bin/sync_cms_to_repo.sh

chore: cleaned up CMS to repo sync script

---

.github/workflows/sync-cms-to-repo.yml

chore: added GitHub action bot as author in git config for GH action

---

site/plugins.json

**Test plan**
https://app.netlify.com/sites/peppy-squirrel-e28c83/deploys/6329be59cf99df000958fe7f

chore(plugins): add snaplet plugin to public directory

---

site/plugins.json

feat: add emails plugin

---

site/plugins.json

chore: update email plugin version

---

site/plugins.json

chore: update emails plugin version

---

site/plugins.json

chore: update emails plugin

---

site/plugins.json

**Test plan**
https://app.netlify.com/sites/wondrous-buttercream-83da75/deploys/632c8242c4109351ac02e370

feat: add inngest plugin to directory

---

site/plugins.json

fix: revert plugin @netlify/plugin-nextjs to version 4.25.0

---

.github/CODEOWNERS

chore(main): switches marketplace naming to integrations

---

site/plugins.json

fix: update Next plugin to 4.27.1

---

site/plugins.json

chore: upgrade emails plugin version

---

site/plugins.json

fix: roll back Next to 4.26.0

---

site/plugins.json

fix: update Next plugin to 4.27.2

---

site/plugins.json

fix: unflag Next.js 4.29.2

---

.github/workflows/publish-workflow-ui.yml
bin/combined_workflow_files.ts
bin/publish_workflow_ui.sh
netlify.toml
site/plugins.json

feat: update FPP with WFUI

---

site/plugins.json

chore: add ff for latest email changes

---

site/plugins.json

feat: pilot to 1.1.11

---

site/plugins.json

chore: update email ff version

---

site/plugins.json

fix: unflag Next.js Runtime 4.29.4

---

site/plugins.json

This needs to be merged in AFTER https://github.com/netlify/plugins/pull/1093 (as the feature flag settings need to be reset)
**Test plan**

feat: increase version of next.js behind feature flag

---

site/plugins.json

fix: update Next runtime ff to 4.30.1

---

site/plugins.json

feat: add feature flagged plugin @netlify/plugin-nextjs as version 4.30.3

---

site/plugins.json

feat: updating @netlify/plugin-gatsby with featureFlag for 3.5.2

---

site/plugins.json

fix: Updated Gatsby featureFlag

---

site/plugins.json

feat: add contentful preview plugin

---

site/plugins.json

feat: add feature flag to v4.31.0 of next runtime

---

site/plugins.json

feat: Updated Gatsby to 3.5.2 and set min to v2

---

site/plugins.json

feat: updating @netlify/plugin-gatsby with featureFlag for 3.6.0

---

site/plugins.json

feat: add feature flag for new version of next runtime

---

site/plugins.json

feat: added Next.js runtime 4.34.0 behind a feature flag

---

site/plugins.json

feat: update plugin @netlify/plugin-gatsby to version 3.6.2

---

site/plugins.json

feat: unflag version 4.35.0 of next-runtime

---

site/plugins.json

feat: add feature flagged v4.36.0 of next-runtime

---

site/plugins.json

feat: unflag version 4.36.0 of next-runtime

---

site/plugins.json

feat: add feature flagged v4.36.1 of next-runtime

---

site/plugins.json

feat: unflag version 4.36.1 of next-runtime

---

site/plugins.json

feat: Add feature flagged v4.37.0 of next-runtime

---

site/plugins.json

feat: unflag version 4.37.1 of next-runtime

---

site/plugins.json

feat: adding feature flag for v4.37.2

---

site/plugins.json

feat: added Next.js runtime 4.38.0 behind a feature flag

---

site/plugins.json

feat: bumped next.js runtime version

---

site/plugins.json

feat: set next-runtime prerelease version to 4.39.4

---

site/plugins.json

feat: added Next.js runtime 4.40.1 behind a feature flag

---

site/plugins.json

This PR only updates the repository URL.
**Test plan**

fix: update cloudinary github url

---

site/plugins.json

feat: added Next.js runtime 4.40.2 behind a feature flag

---

site/plugins.json

feat: added Next.js runtime 4.41.1 behind a feature flag

---

site/plugins.json

Adding the new angular plugin. It's not released yet, so we should hold off on this PR until that's done.
https://linear.app/netlify/issue/COM-126/refresh-angular-plugin-for-v17
**Test plan**

feat: add new angular plugin

---

site/plugins.json

https://github.com/netlify/angular-runtime/pull/77 isn't released yet - but i'm opening this PR already so I can get an approval, and I can merge it quickly once the new version is released :)

fix: Update Angular plugin

---

site/plugins.json

feat: update plugin @netlify/plugin-nextjs to flagged version 4.41.2

---

site/plugins.json

feat: update cloudinary version

---

site/plugins.json

feat: add new next runtime 5.0.0-beta.0 behind a feature flag

---

site/plugins.json
test/main.js

feat: adapt the release constraints for next runtime 5.0.0-beta.0

---

site/plugins.json

feat: update the beta of the next runtime

---

site/plugins.json

chore: Update plugins.json for emails integration

---

site/plugins.json

fix: update Cloudinary to 1.17.0

---

site/plugins.json

feat: set next.js minimal runtime to 5.0.0-rc.3

---

site/plugins.json

feat: update Next runtime to rc.5

---

site/plugins.json
test/main.js

Deactivates a plugin for which the repo is now a 404. It also skips a specific test for deactivated plugins.

fix: deactivate plugin

---

site/plugins.json

feat: update Next runtime to rc.8

---

site/plugins.json

feat: update Next runtime to 5.0.0 behind gradual rollout feature flag and opt-in

---

site/plugins.json

feat: update Next runtime to 5.1.0 behind gradual rollout feature flag and opt-in

---

site/plugins.json

feat: update plugin @netlify/plugin-gatsby to version 3.8.1

---

site/plugins.json

feat: update Next runtime to 5.1.1 behind gradual rollout feature flag and opt-in

---

site/plugins.json

feat: update Next runtime to 5.1.2 behind gradual rollout feature flag and opt-in

---

site/plugins.json

feat: roll out Next runtime 5.2.0 behind flag

---

site/plugins.json

fix: update Angular runtime to 2.0.7

---

site/plugins.json

feat: update flagged Next to 5.3.0

---

site/plugins.json

feat: update Angular runtime to 2.1.0

---

site/plugins.json

feat: bump @netlify/plugin-nextjs to 5.5.1

---

site/plugins.json

feat: bump next runtime to 5.6.0

---

site/plugins.json

feat: bump next runtime to 5.7.0

---

site/plugins.json

feat: bump next runtime to 5.7.1

---

site/plugins.json

feat: bump next runtime to 5.7.2

---

site/plugins.json

feat: bump next runtime to 5.7.3

---

site/plugins.json

feat: bump next runtime to 5.7.4

---

site/plugins.json

feat: bump next runtime to 5.8.0

---

site/plugins.json

feat: update plugin @netlify/angular-runtime to version 2.2.0

---

site/plugins.json

feat: update plugin @netlify/angular-runtime to version 2.2.1

---

site/plugins.json

feat: update plugin @netlify/plugin-nextjs to version 5.9.0

---

site/plugins.json

feat: update plugin @netlify/plugin-nextjs to version 5.9.1

---

site/plugins.json

feat: update plugin @netlify/plugin-nextjs to version 5.9.2

---

site/plugins.json

feat: update plugin @netlify/plugin-nextjs to version 5.9.3

---

site/plugins.json

chore: bump next runtime to 5.10.0

---

site/plugins.json

chore: bump angular runtime to 2.3.0

---

site/plugins.json

feat: update plugin @netlify/plugin-gatsby to version 3.8.3

---

site/plugins.json

chore: bump next runtime to 5.10.3

---

site/plugins.json

chore: bump next runtime to 5.10.4

---

site/plugins.json

chore: bump next runtime to 5.10.5

---

site/plugins.json

chore: update next runtime version to v5.11.0

---

site/plugins.json

fix(deps): update next plugin to 5.11.3

---

site/plugins.json

chore: upgrade next plugin to 5.11.4
